### ISSUE TITLE
avoid repeated downloading of mapnik-win-sdk-binary-deps-14.0-x64.7z

### ISSUE THREAD

**Issue by springmeyer** [mapbox/windows-builds#45] opened 2015-06-12 17:43 UTC
It seems like re-running `scripts/build_mapnik.bat` locally I always wait for the 7z download. Or it seems like it since the script hangs for ~5 seconds on this step. Not looked closely yet, but ideally this could be optimized to help with debugging code changes.

```
"checking for mapnik-win-sdk-binary-deps-14.0-x64.7z"
"downloading http://mapnik.s3.amazonaws.com/deps/mapnik-win-sdk-binary-deps-14.0-x64.7z"
Processing archive: mapnik-win-sdk-binary-deps-14.0-x64.7z
```

**Comment by BergWerkGIS** [comment] 2015-06-13 08:00
Closing, duplicate of #34

**Closed by BergWerkGIS** 2015-06-13 08:00 UTC
